trigger:
- neos-release

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      sourceFolder: ''
      sourceFile: 'libfreetype.so'
      targetFile: 'libfreetype6.so'
      artifactName : 'linux_x64'
      buildCommand: | 
        mkdir build && cd build
        cmake .. -D BUILD_SHARED_LIBS=true -D CMAKE_BUILD_TYPE=Release
        make
        tree
    windows:
      imageName: 'windows-latest'
      sourceFolder: 'objs\'
      sourceFile: 'freetype.dll'
      targetFile: 'freetype6.dll'
      artifactName : 'windows_x64'
    android:
      imageName: 'windows-latest'
      sourceFolder: 'builds\android\libs\armeabi-v7a\'
      sourceFile: 'libfreetype6.so'
      targetFile: 'libfreetype6.so'
      buildCommand: | 
        cd builds
        cd android
        $(ANDROID_NDK_PATH)/ndk-build
        tree /A /F


pool:
  vmImage: $(imageName)

steps:
- task: VSBuild@1
  inputs:
    solution: 'builds\windows\vc2010\freetype.sln'
    platform: 'x64'
    configuration: 'Release'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'
  condition: eq( variables['Agent.JobName'], 'Job windows' )

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '$(buildCommand)'
  condition: eq( variables['Agent.OS'], 'Linux' )

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$(buildCommand)'
  condition: eq( variables['Agent.JobName'], 'Job android' )

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(sourceFolder)'
    Contents: '$(sourceFile)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'mv ''$(build.artifactstagingdirectory)/$(sourceFile)'' ''$(build.artifactstagingdirectory)/$(targetFile)'''

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'